apiVersion: apps/v1
kind: Deployment
metadata:
  name: productivity-service
spec:
  selector:
    matchLabels:
      app: productivity-service
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: productivity-service
    spec:
      containers:
        - name: productivity-service
          image: gcr.io/PROJECT_ID/IMAGE:TAG
          imagePullPolicy: Always
          env:
          - name: spring_profiles_active
            value: qa
          ports:
            - containerPort: 9193