apiVersion: v1
kind: Service
metadata:
  name: productivity-service-service
  labels:
    app: productivity-service
  namespace: default
spec:
  selector:
    app: productivity-service
  ports:
    - protocol: "TCP"
      port: 9193
      targetPort: 9193
      nodePort: 30448
  type: NodePort